---
# Coolify-optimized Docker Compose configuration
# Set environment variables in Coolify's UI (see .env.coolify.example)

services:
  php:
    build:
      context: .
      target: frankenphp_prod
    image: app-php
    restart: unless-stopped
    environment:
      # Server configuration
      SERVER_NAME: ${SERVER_NAME}, php:80
      APP_ENV: prod
      APP_PORT: ${APP_PORT}

      # Security secrets (REQUIRED - set in Coolify)
      APP_SECRET: ${APP_SECRET}

      # Database connection (REQUIRED - use Coolify's database service)
      DATABASE_URL: ${DATABASE_URL}

      # Mercure configuration (REQUIRED - set in Coolify)
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

    volumes:
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT}
        protocol: udp

volumes:
  caddy_data:
  caddy_config:
